/**
 * Phase SMART-2 — pure workflow helpers.
 *
 * Composition + comparison logic shared by the reschedule and
 * cancellation-recovery orchestrators. NO DB I/O — pure functions
 * over the ScoredSlot[] output of SMART-1 + the customer's currently-
 * booked time (when applicable).
 *
 * Determinism contract: every export is a pure function. Same
 * inputs → same outputs. No Math.random, no Date.now (callers pass
 * `now` or `referenceTime`).
 */

import type {
  FactorScore,
  ScoredSlot,
} from "@/lib/scheduling/intelligence/types";

import {
  MAX_RECOMMENDATIONS,
  type TimeOfDay,
  type WorkflowComparison,
  type WorkflowHeadline,
  type WorkflowRecommendation,
} from "./types";

// ─── Time-of-day bucketing (deterministic) ────────────────────────────

/** Bucket a UTC date into a coarse time-of-day in the given IANA
 *  timezone. Used for headline phrasing ("Morning alternative",
 *  "Afternoon slot opens"). */
export function bucketTimeOfDay(d: Date, tz: string): TimeOfDay {
  const fmt = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    hour: "2-digit",
    hour12: false,
  });
  const h = parseInt(fmt.format(d), 10);
  const hour = h === 24 ? 0 : h;
  if (hour < 8) return "early-morning";
  if (hour < 12) return "morning";
  if (hour < 14) return "midday";
  if (hour < 18) return "afternoon";
  return "evening";
}

/** Same-calendar-day check in the given timezone. */
export function isSameDayInTz(a: Date, b: Date, tz: string): boolean {
  const fmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  return fmt.format(a) === fmt.format(b);
}

// ─── Comparison tagging ──────────────────────────────────────────────

/** Tag a candidate slot relative to a reference time + the
 *  position-in-list. The first item in the rec list gets
 *  `first_available` when its score is decent (≥60) so the UI can
 *  surface "Earliest available" prominently. */
export function tagComparison(args: {
  slotStart: Date;
  referenceTime: Date | null;
  isFirstInList: boolean;
  score: number;
  tz: string;
}): WorkflowComparison {
  const { slotStart, referenceTime, isFirstInList, score, tz } = args;
  if (isFirstInList && score >= 60 && referenceTime === null) {
    return "first_available";
  }
  if (referenceTime === null) {
    // No comparison anchor — default to first_available for top, else different_day.
    return isFirstInList && score >= 60 ? "first_available" : "different_day";
  }
  if (slotStart.getTime() < referenceTime.getTime()) {
    return "earlier";
  }
  if (isSameDayInTz(slotStart, referenceTime, tz)) {
    return "same_day";
  }
  return "different_day";
}

// ─── Reasoning generation (template-rendered, NOT LLM) ───────────────

/** Render deterministic reasoning lines from a SMART-1 factor
 *  breakdown. Each line is generated by a fixed template + the
 *  factor's score crossing a fixed threshold. The lines are
 *  IDENTICAL across calls for the same input — zero generative AI.
 *
 *  Up to 3 lines, in priority order. Never empty: a slot with
 *  unremarkable scores gets the generic "Available + no
 *  scheduling conflicts" line. */
export function generateReasoning(breakdown: FactorScore[] | undefined): string[] {
  const lines: string[] = [];
  if (!breakdown) return ["Available — no scheduling conflicts."];

  // Map factor names → quick lookup for threshold checks.
  const byFactor = new Map(breakdown.map((f) => [f.factor, f]));

  // 1. Time-of-day strength.
  const tod = byFactor.get("timeOfDay");
  if (tod && tod.score >= 90) {
    lines.push("Peak booking hour — typically high attendance.");
  } else if (tod && tod.score >= 75) {
    lines.push("Favorable time of day.");
  }

  // 2. Customer history hit.
  const cp = byFactor.get("customerPreference");
  if (cp && cp.score >= 85) {
    lines.push("Matches your usual booking time.");
  }

  // 3. Workload + density (fairness).
  const wb = byFactor.get("workloadBalance");
  const dd = byFactor.get("dailyDensity");
  if (wb && wb.score === 100 && dd && dd.score >= 80) {
    lines.push("Light schedule — quick confirmation likely.");
  }

  // 4. Focus block respected.
  const fb = byFactor.get("focusBlockRespect");
  if (fb && fb.score === 100) {
    // No-op if we already have positive lines.
    if (lines.length === 0) lines.push("Outside any focus-time blocks.");
  }

  // 5. Buffer efficiency.
  const be = byFactor.get("bufferEfficiency");
  if (be && be.score === 100 && lines.length < 3) {
    lines.push("Clean buffer — no back-to-back stress.");
  }

  // 6. Lunch avoidance.
  const la = byFactor.get("lunchAvoidance");
  if (la && la.score < 80 && lines.length < 3) {
    lines.push("Overlaps lunch — may be less ideal.");
  }

  // 7. End of day fatigue.
  const eod = byFactor.get("endOfDayFatigue");
  if (eod && eod.score < 75 && lines.length < 3) {
    lines.push("Late in the working day.");
  }

  if (lines.length === 0) {
    lines.push("Available — no scheduling conflicts.");
  }

  return lines.slice(0, 3);
}

// ─── Headline composition (template-rendered) ────────────────────────

/** Format a slot time as "Mon 10:00 AM" in the given timezone.
 *  Deterministic — Intl with fixed format. */
export function formatHeadlineTime(d: Date, tz: string): string {
  const day = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    weekday: "short",
  }).format(d);
  const time = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  }).format(d);
  return `${day} ${time}`;
}

/** Compose a single-sentence headline from the top recommendation.
 *  Returns null when no slot scores high enough to confidently
 *  highlight. */
export function buildHeadline(args: {
  top: WorkflowRecommendation | undefined;
  referenceTime: Date | null;
  tz: string;
}): WorkflowHeadline | null {
  const { top, referenceTime, tz } = args;
  if (!top || top.score < 70) return null;
  const formatted = formatHeadlineTime(new Date(top.time), tz);
  let prefix = "Best alternative";
  if (top.comparison === "earlier") prefix = "Earlier slot available";
  else if (top.comparison === "first_available") prefix = "Earliest available";
  else if (top.comparison === "same_day") prefix = "Same-day option";
  return {
    text: `${prefix}: ${formatted}`,
    highlightSlot: top.time,
  };
}

// ─── Promotion: ScoredSlot[] → WorkflowRecommendation[] ──────────────

/** Pick top-N scored slots, tag with workflow comparison + reasoning,
 *  return as a WorkflowRecommendation list. The cap is enforced at
 *  MAX_RECOMMENDATIONS (3) so the UI never floods the user.
 *
 *  Sort: score DESC, then time ASC (deterministic tiebreak). */
export function promoteRecommendations(args: {
  scoredSlots: ScoredSlot[];
  referenceTime: Date | null;
  tz: string;
  limit?: number;
}): WorkflowRecommendation[] {
  const { scoredSlots, referenceTime, tz, limit = MAX_RECOMMENDATIONS } = args;
  if (scoredSlots.length === 0) return [];

  // Sort: score DESC, then time ASC.
  const sorted = [...scoredSlots].sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return a.time.localeCompare(b.time);
  });

  return sorted.slice(0, limit).map((s, idx) => {
    const slotStart = new Date(s.time);
    const deltaMinutes = referenceTime
      ? Math.round((slotStart.getTime() - referenceTime.getTime()) / 60_000)
      : null;
    const comparison = tagComparison({
      slotStart,
      referenceTime,
      isFirstInList: idx === 0,
      score: s.score,
      tz,
    });
    return {
      time: s.time,
      score: s.score,
      labels: s.labels,
      reasoning: generateReasoning(s.breakdown),
      deltaMinutes,
      comparison,
    };
  });
}
