/**
 * Closed taxonomy for the downgrade enforcement orchestrator.
 *
 * Three axes:
 *   - EnforcementMode: HOW we enforce (soft/grandfathered/hard)
 *   - ActionKind: WHAT we do to a row (pause_series / disable_rule / ...)
 *   - ActionStatus: outcome of an executor run for a single action
 *
 * Every union is closed — adding a new mode/action requires editing
 * this file AND wiring it in the executor + policies. That intentional
 * friction is the safety boundary: an executor switch on `kind` with
 * no default branch will fail to compile when a new kind is added,
 * forcing the engineer to think about it.
 */
import type { Capability } from "@/lib/billing/capabilities";
import type { PlanId } from "@/lib/plans";

// ─── Mode ─────────────────────────────────────────────────────────────

export const ENFORCEMENT_MODES = ["soft", "grandfathered", "hard"] as const;
export type EnforcementMode = (typeof ENFORCEMENT_MODES)[number];

export function isEnforcementMode(s: string): s is EnforcementMode {
  return (ENFORCEMENT_MODES as readonly string[]).includes(s);
}

// ─── Action ───────────────────────────────────────────────────────────

/**
 * Every concrete thing the executor can do, per-feature, on downgrade.
 * Each kind maps to a handler in executor.ts. Adding a new kind:
 *   1. Add it here.
 *   2. Add a case to the executor switch (compiler will catch the
 *      missing case).
 *   3. Document in the audit log shape.
 *
 * Recovery (upgrade) actions live in the parallel `RecoveryActionKind`
 * union so the executor and recovery code paths can't be accidentally
 * crossed.
 */
export const DOWNGRADE_ACTION_KINDS = [
  // RECURRING — implemented in this commit
  "pause_recurring_series",

  // The following are PLANNED-ONLY in this commit. The action planner
  // emits them so the operator can see what the orchestrator WOULD do
  // when handlers ship; the executor logs them as "not_implemented".
  "disable_automation_rules",
  "disable_routing_rules_premium_modes",
  "deactivate_custom_domains",
  "freeze_excess_locations",
  "freeze_excess_services",
  "freeze_excess_staff_seats",
  "lock_analytics_export",
] as const;
export type DowngradeActionKind = (typeof DOWNGRADE_ACTION_KINDS)[number];

export const RECOVERY_ACTION_KINDS = [
  "resume_recurring_series",

  // Planned-only counterparts.
  "enable_automation_rules",
  "enable_routing_rules_premium_modes",
  "reactivate_custom_domains",
  "unfreeze_excess_locations",
  "unfreeze_excess_services",
  "unfreeze_excess_staff_seats",
  "unlock_analytics_export",
] as const;
export type RecoveryActionKind = (typeof RECOVERY_ACTION_KINDS)[number];

// ─── Planned action shape ─────────────────────────────────────────────

/**
 * One concrete row-level action the orchestrator intends to take.
 * Pure data — generated by the planner, consumed by the executor.
 * `entityIds` are the specific rows that would be affected so the
 * dry-run output is auditable ("would pause series IDs [...]").
 */
export type DowngradeAction = {
  kind: DowngradeActionKind;
  capability: Capability;
  mode: EnforcementMode;
  /** Specific row IDs (booking_series.id, etc.) that would be touched.
   *  Empty array means "no rows match the filter" — the action is
   *  emitted for completeness/audit but is effectively a no-op. */
  entityIds: string[];
  /** Customer-facing label for UI surfaces (admin tools, ops dashboards). */
  description: string;
};

export type RecoveryAction = {
  kind: RecoveryActionKind;
  capability: Capability;
  /** Specific row IDs to restore. Usually populated from the
   *  `enforcement_event_id` marker so we restore EXACTLY what we paused. */
  entityIds: string[];
  description: string;
};

// ─── Plan envelope ────────────────────────────────────────────────────

export type DowngradePlan = {
  tenantId: string;
  fromPlan: PlanId;
  toPlan: PlanId;
  /** Stripe event ID (or "manual:<admin>") for idempotency + audit.
   *  Re-running the executor with the same eventId is a no-op for
   *  rows already marked with this id. */
  eventId: string;
  actions: DowngradeAction[];
  /** Human-readable summary safe to render in admin tools. */
  summary: string;
};

export type RecoveryPlan = {
  tenantId: string;
  fromPlan: PlanId;
  toPlan: PlanId;
  eventId: string;
  actions: RecoveryAction[];
  summary: string;
};

// ─── Execution result ─────────────────────────────────────────────────

export type ActionStatus =
  | "applied"        // mutation happened
  | "skipped_idempotent" // row already in target state under this event_id
  | "skipped_dry_run"    // dry-run mode; would have applied
  | "not_implemented"    // handler stubbed for this commit
  | "failed";            // an error fired; logged + action recorded for retry

export type ActionResult = {
  kind: DowngradeActionKind | RecoveryActionKind;
  capability: Capability;
  status: ActionStatus;
  affected: number;
  error?: string;
};

export type ExecutionResult = {
  tenantId: string;
  eventId: string;
  dryRun: boolean;
  results: ActionResult[];
  /** True only when every action.status is in {"applied",
   *  "skipped_idempotent", "skipped_dry_run", "not_implemented"}. Any
   *  "failed" makes this false. Caller decides whether to retry. */
  ok: boolean;
};
